version: '3'
services:
  postgres:
    image: postgres:11
    ports:
    - 5432:5432
    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
    - ./compose/postgres:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3
  email:
    image: djfarrelly/maildev
    ports:
    - 1080:80
  frontend:
    image: node:lts-slim
    working_dir: /opt/app
    user: "1000"
    volumes:
    - .:/opt/app
    command: sh -c "npm i && npm run watch"
  learning-circles:
    build: .
    image: p2pu/learning-circles:local
    ports:
    - 8000:8000
    volumes:
    - .:/opt/app
    depends_on:
    - rabbitmq
    - postgres
    - email
    - frontend
    env_file: docker.env
    environment:
    - ADMIN_EMAIL=admin@localhost
    - BROKER_URL=amqp://guest:guest@rabbitmq//
    - COMMUNITY_MANAGER=user@mail.com
    - DATABASE_URL=postgres://lc:password@postgres:5432/lc
    - DEBUG=true
    - DEFAULT_FROM_EMAIL=notify@mail.com
    - EMAIL_HOST=email
    - PROTOCOL=http
    - SECRET_KEY=321
    command: /opt/django-venv/bin/python manage.py runserver 0.0.0.0:8000
  celery:
    image: p2pu/learning-circles:local
    depends_on:
    - rabbitmq
    - postgres
    - email
    user: celery
    volumes:
    - .:/opt/app
    working_dir: /opt/app
    command: /opt/django-venv/bin/celery -A learnwithpeople worker --loglevel=INFO
    env_file: docker.env
    environment:
    - ADMIN_EMAIL=admin@localhost
    - BROKER_URL=amqp://guest:guest@rabbitmq//
    - COMMUNITY_MANAGER=user@mail.com
    - DATABASE_URL=postgres://lc:password@postgres:5432/lc
    - DEBUG=true
    - DEFAULT_FROM_EMAIL=notify@mail.com
    - EMAIL_HOST=email
    - PROTOCOL=http
    - SECRET_KEY=321
  celery-beat:
    image: p2pu/learning-circles:local
    depends_on:
    - rabbitmq
    - postgres
    user: celery
    volumes:
    - .:/opt/app
    working_dir: /opt/app
    command: /opt/django-venv/bin/celery -A learnwithpeople beat --loglevel=DEBUG --schedule=/var/lib/celery/celerybeat-schedule
    env_file: docker.env
    environment:
    - DATABASE_URL=postgres://lc:password@postgres:5432/lc
    - SECRET_KEY=321
    - BROKER_URL=amqp://guest:guest@rabbitmq//
