version: '3'
services:
  postgres:
    image: postgres
  email:
    image: djfarrelly/maildev
    ports:
    - 1080:80
  learning-circles:
    build: .
    image: learning-circles
    ports:
    - "8000:8000"
    volumes:
    - .:/opt/app
    depends_on:
    - postgres
    - email
    command: /opt/django-venv/bin/python manage.py runserver 0.0.0.0:8000
    environment:
    - DATABASE_URL=postgres://lc:password@postgres:5432/lc
    - SECRET_KEY=321
    - BROKER_URL=amqp://guest:guest@rabbitmq//
    - EMAIL_HOST=email
    - COMMUNITY_MANAGER=user@mail.com
    - DEFAULT_FROM_EMAIL=notify@mail.com
    - DEBUG=true
  frontend:
    image: p2pu/js-build:carbon-alpine
    volumes:
    - .:/opt/app
    working_dir: /opt/app
    command: sh -c "npm i --no-optional && npm run watch"

